name: gz-env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - ampl-asl=1.0.0=h5888daf_2
  - aom=3.9.1=hac33072_0
  - assimp=5.4.3=hecf2907_1
  - attr=2.5.2=h39aace5_0
  - aws-c-auth=0.9.1=h7ca4310_7
  - aws-c-cal=0.9.10=h346e085_1
  - aws-c-common=0.12.5=hb03c661_1
  - aws-c-compression=0.3.1=h7e655bb_8
  - aws-c-event-stream=0.5.6=h3cb25bf_6
  - aws-c-http=0.10.7=hc5c8343_4
  - aws-c-io=0.23.3=ha76f1cc_3
  - aws-c-mqtt=0.13.3=h3a25ec9_10
  - aws-c-s3=0.10.1=hcb69869_2
  - aws-c-sdkutils=0.2.4=h7e655bb_3
  - aws-checksums=0.2.7=h7e655bb_4
  - aws-crt-cpp=0.35.2=h2ceb62e_4
  - aws-sdk-cpp=1.11.606=hd6e39bc_7
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - blis=0.9.0=h4ab18f5_2
  - blosc=1.21.6=he440d0b_1
  - bullet-cpp=3.25=ha87cce1_5
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - capnproto=1.2.0=hfc315d8_0
  - cfitsio=4.6.3=ha0b56bc_0
  - cli11=2.6.0=h54a6638_0
  - cmake=4.1.2=hc85cc9f_0
  - collada-dom=2.5.0=hd82f57d_13
  - console_bridge=1.0.2=h924138e_1
  - cppzmq=4.10.0=h2e2a08d_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dartsim-cpp=6.15.0=h7c77dc3_13
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - double-conversion=3.3.1=h5888daf_0
  - eigen=3.4.0=h171cf75_1
  - elfutils=0.193=h849f50c_0
  - expat=2.7.1=hecca717_0
  - fcl=0.7.0=h543440a_8
  - ffmpeg=8.0.0=gpl_hbbdf940_906
  - flann=1.9.2=hc299af7_5
  - fmt=12.0.0=h2b0788b_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freeglut=3.2.2=ha6d2627_3
  - freeimage=3.18.0=h165c975_23
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - fribidi=1.0.16=hb03c661_0
  - gdbm=1.18=h0a1914f_2
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - geos=3.14.1=h480dda7_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=hd590300_0
  - glfw=3.4=hb03c661_1
  - glib=2.86.0=he175458_0
  - glib-tools=2.86.0=hf516916_0
  - glslang=16.0.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.8.9=h86084c0_1
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.26.3=hfe64121_1
  - gstreamer=1.26.3=h17cb667_1
  - gz-cmake4=4.2.0=h83e9d05_1
  - gz-sim=10.0.0=py313h56a4ca9_2
  - gz-sim-python=10.0.0=py313hd06b445_2
  - harfbuzz=12.1.0=h15599e2_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - icu=75.1=he02047a_0
  - imath=3.2.1=hde8ca8f_0
  - imgui=1.92.3=hc6652ba_0
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - ipopt=3.14.19=h6c08d29_1
  - jasper=4.2.8=he3c4edf_0
  - json-c=0.18=h6688a6e_0
  - jsoncpp=1.9.6=hf42df4d_1
  - jxrlib=1.1=hd590300_3
  - kealib=1.6.2=hb2f3951_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=h1aa0949_0
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.26.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libadbc-driver-manager=1.8.0=hb700be7_1
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.2=gpl_h7be2006_100
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=39_h91f140b_blis
  - libboost=1.88.0=hed09d94_6
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcap=2.77=h3ff7636_0
  - libcblas=3.9.0=39_h3c44731_blis
  - libccd-double=2.1=h59595ed_3
  - libclang-cpp21.1=21.1.5=default_h99862b1_1
  - libclang13=21.1.5=default_h746c552_1
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgdal=3.11.4=h3b705f5_9
  - libgdal-adbc=3.11.4=hdee084c_8
  - libgdal-core=3.11.4=hf57b35e_8
  - libgdal-fits=3.11.4=hec9d828_8
  - libgdal-grib=3.11.4=hb20eef8_8
  - libgdal-hdf4=3.11.4=ha810028_8
  - libgdal-hdf5=3.11.4=h966a9c2_8
  - libgdal-jp2openjpeg=3.11.4=hdd07572_8
  - libgdal-kea=3.11.4=h2bf108d_8
  - libgdal-netcdf=3.11.4=ha526aae_8
  - libgdal-pdf=3.11.4=h20efda7_8
  - libgdal-pg=3.11.4=h55c2262_8
  - libgdal-postgisraster=3.11.4=h55c2262_8
  - libgdal-tiledb=3.11.4=h6c35068_8
  - libgdal-xls=3.11.4=hdee084c_8
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libgl-devel=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libglx-devel=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libgz-cmake=5.0.0=h54a6638_0
  - libgz-cmake4=4.2.0=h54a6638_1
  - libgz-common=7.0.0=h21264d5_1
  - libgz-fuel-tools=11.0.0=h9aa1ebb_0
  - libgz-gui=10.0.0=h331da0e_0
  - libgz-math=9.0.0=h04f07ea_0
  - libgz-msgs=12.0.0=h4f0e29b_1
  - libgz-physics=9.0.0=h66d7660_0
  - libgz-plugin=4.0.0=h93f228a_0
  - libgz-rendering=10.0.0=heeb8b46_0
  - libgz-sensors=10.0.0=h87426f2_0
  - libgz-sim=10.0.0=py313h2786f13_2
  - libgz-tools=2.0.3=h54a6638_1
  - libgz-transport=15.0.0=h5684bc9_0
  - libgz-utils=4.0.0=h6343034_1
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=hf08fa70_5
  - libkml=1.3.0=haa4a5bd_1022
  - liblapack=3.9.0=13_h8876d29_netlib
  - liblapacke=3.9.0=13_hb041515_netlib
  - libllvm21=21.1.5=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmicrohttpd=1.0.2=hc2fc477_0
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnetcdf=4.9.3=nompi_h11f7409_103
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libode=0.16.5=h7469f36_0
  - libogg=1.3.5=hd0c01bc_1
  - libopencv=4.12.0=qt6_py313he1716e0_604
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libprotobuf=6.31.1=h49aed37_2
  - libraw=0.21.4=h9969a89_0
  - libre2-11=2025.11.05=h7b12aa8_0
  - librsvg=2.60.0=h61e6d4b_0
  - librttopo=1.1.0=h46dd2a8_20
  - libscotch=7.0.10=int32_h6f2090f_1
  - libsdformat=16.0.0=py310h35f791f_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libspatialite=5.1.0=gpl_h2abfd87_119
  - libspral=2025.05.20=hfabd9d1_1
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=258.2=h6569c3e_1
  - libtasn1=4.20.0=hb03c661_1
  - libtiff=4.7.1=h8261f1e_0
  - libudev1=258.2=h6569c3e_1
  - libunistring=0.9.10=h7f98852_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.0=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxml2-devel=2.15.1=h26afc86_0
  - libxslt=1.1.43=h711ed8c_1
  - libzenohc=1.5.1=hfad6b34_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - meson=1.9.1=pyhcf101f3_0
  - metis=5.1.0=hd0bcaf9_1007
  - minizip=4.0.10=h05a5f5f_0
  - mpg123=1.32.9=hc50e24c_0
  - mumps-include=5.8.1=h1795ed4_4
  - mumps-seq=5.8.1=h4374b6a_4
  - muparser=2.3.5=h5888daf_0
  - ncurses=6.5=h2d0b736_3
  - nettle=3.10.1=h4a9d5aa_0
  - ninja=1.13.1=h171cf75_0
  - nlopt=2.10.0=py313h190977b_1
  - nspr=4.38=h29cc59b_0
  - nss=3.117=h445c969_0
  - numpy=2.3.4=py313hf6604e3_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - octomap=1.10.0=h84d6215_0
  - ogre=1.10.12.1=he8a7676_7
  - ogre-next=2.3.3=ha916a4f_1
  - opencl-headers=2025.06.13=h5888daf_0
  - opencv=4.12.0=qt6_py313h6537eeb_604
  - openexr=3.3.5=h608838b_1
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openscenegraph=3.6.5=h6fe4003_20
  - openssl=3.6.0=h26f9b46_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - pagmo=2.19.1=h9d79fbf_8
  - pango=1.56.4=hadf4263_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.46=h1321c63_0
  - pixman=0.46.4=h54a6638_1
  - poppler=25.07.0=h13eef12_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=18.0=hd2008fe_0
  - proj=9.7.0=hb72c0af_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a8bead_2
  - py-opencv=4.12.0=qt6_py313hc0a75a6_604
  - pybind11-abi=11=hc364b38_1
  - python=3.13.9=h2b335a9_100_cp313
  - python_abi=3.13=8_cp313
  - qt6-main=6.9.3=h5c1c036_1
  - rapidjson=1.1.0.post20240409=h3f2d84a_2
  - rav1e=0.7.1=h8fae777_3
  - re2=2025.11.05=h5301d42_0
  - readline=8.2=h8c095d6_2
  - rhash=1.4.6=hb9d3cd8_1
  - ruby=3.4.7=hd8161a3_0
  - s2n=1.6.0=h8399546_1
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.26=h68140b3_0
  - shaderc=2025.4=h3e344bc_0
  - snappy=1.2.2=h03e3b7b_1
  - spdlog=1.16.0=hffee6e0_1
  - spirv-tools=2025.4=hb700be7_0
  - sqlite=3.51.0=heff268d_0
  - svt-av1=3.1.2=hecca717_0
  - swig=4.4.0=hf1419ba_1
  - tbb=2022.3.0=h8d10470_1
  - tiledb=2.29.2=h8821262_1
  - tinyxml2=11.0.0=h3f2d84a_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tzcode=2025b=hb9d3cd8_0
  - tzdata=2025b=h78e105d_0
  - urdfdom=4.0.1=hae71d53_3
  - urdfdom_headers=1.1.2=h84d6215_0
  - uriparser=0.9.8=hac33072_0
  - uv=0.9.9=h76e24b7_0
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xerces-c=3.3.0=h988505b_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxaw=1.0.16=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxmu=1.2.1=hb9d3cd8_1
  - xorg-libxpm=3.5.17=hb9d3cd8_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - yaml=0.2.5=h280c20c_3
  - zenoh-rust-abi=1.5.1.1.85.0=h8619998_0
  - zeromq=4.3.5=h387f397_9
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - zziplib=0.13.69=he45264a_2
  - pip:
      - dronecan==1.0.27
      - empy==4.2
      - fastcrc==0.3.4
      - future==1.0.0
      - lxml==6.0.2
      - mavproxy==1.8.74
      - osascript==2020.12.3
      - pexpect==4.9.0
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pymavlink==2.4.49
      - pynmeagps==1.0.56
      - pyserial==3.5
      - runcmd==2020.12.3
variables:
  GZ_SIM_SYSTEM_PLUGIN_PATH: 'ardupilot_gazebo/build:'
  GZ_SIM_RESOURCE_PATH: 'ardupilot_gazebo/worlds:ardupilot_gazebo/models:sitl_models/Gazebo/models/:sitl_models/Gazebo/worlds/:'
  GZ_PLUGIN_PATH: 'ardupilot_gazebo/build'
  GZ_VERSION: 'jetty'
